### ISSUE TITLE
"plugin: unknown plugin type: rewrite-body"

### ISSUE THREAD

**Issue by ArkaHnat** [packruler/rewrite-body#18]
**Describe the bug**
Configuration provided in example doesn't work. I tried to use example from https://github.com/packruler/rewrite-body.

**Relevant Config**
docker-compose.yml
```
services:
  traefik:
    image: "traefik:v2.4"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/conf-static.yml:/etc/traefik/traefik.yaml:ro
      - ./traefik/conf-dynamic.yml:/etc/traefik/dynamic_config.yml:ro
      - ./traefik/certs:/letsencrypt
```

static configuration:
```
global:
  checkNewVersion: true
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entrypoint:
          to: :30002
          scheme: "https"
  websecure:
    address: ":443"
providers:
  file:
    filename: "/etc/traefik/dynamic_config.yml"
    watch: true
experimental:
  plugins:
    plugin-rewritebody:
      moduleName: "github.com/traefik/plugin-rewritebody"
      version: "v0.3.1"
    rewrite-body:
      moduleName: "github.com/packruler/rewrite-body"
      version: "v1.1.0"
```

dynamic configuration:
```
http:
  routers:
    my-router:
      rule: "Host(`localhost`)"
      middlewares:
        - "rewrite-foo"
      service: "my-service"
  middlewares:
    rewrite-foo:
      plugin:
        rewrite-body:
          lastModified: true
          rewrites:
            - regex: "foo"
              replacement: "bar"
          logLevel: 0
          monitoring:
            methods:
              - GET
            types:
              - text/html
  services:
    my-service:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1"

```

**Expected behavior**
Traefik should start without error

**Actual behavior**
When starting I'm getting following error:
traefik_t        | time="2023-07-27T08:24:49Z" level=info msg="Configuration loaded from file: /etc/traefik/traefik.yaml"
traefik_t        | time="2023-07-27T08:24:49Z" level=error msg="plugin: unknown plugin type: rewrite-body" entryPointName=web routerName=my-router@file
traefik_t        | time="2023-07-27T08:24:49Z" level=error msg="plugin: unknown plugin type: rewrite-body" entryPointName=websecure routerName=my-router@file

```
